# --- PERMANENT BLUE LIGHT FILTER ---

# Max strength (optional cap, 1.0 = standard)
max-gamma = 1.0

profile {
    time = 00:00
    # 6500 is default (blue/white). Lower = Warmer/More Orange.
    # 4500 is a good "all day" paper-like look.
    # 3500 is very warm/orange (heavy filter).
    temperature = 3500 
    gamma = 1.0
}
