exec-once = waybar
exec-once = hyprpaper
exec-once = mako
exec-once = hypridle
exec-once = hyprsunset -t 3000
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = gsettings set org.gnome.desktop.interface cursor-size 16
exec-once = mpd
