workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule {
    name = no-border-single
    match:float = false
    match:workspace = w[tv1]
    border_size = 0
    rounding = 0
}

windowrule {
    name = no-border-fullscreen
    match:float = false
    match:workspace = f[1]
    border_size = 0
    rounding = 0
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Yazi terminal popup
windowrule = match:class ^yazi-term$, float on, size monitor_w*0.8 monitor_h*0.8, rounding 12, center on

# nmtui network manager popup
windowrule = match:class ^impala-float$, float on, size monitor_w*0.4 monitor_h*0.6, rounding 12, center on

# Layer rules
layerrule = no_anim on, match:namespace launcher
