[opener]
edit = [
    { run = '${EDITOR:-vi} "$@"', block = true, for = "unix" },
]
scim = [
    { run = 'kitty -e sc-im "$@"', block = true, for = "unix" },
]

[open]
prepend_rules = [
    { name = "*.csv", use = [ "scim", "edit" ] },
    { mime = "text/csv", use = [ "scim", "edit" ] },
]
